title: alexth4ef9 blog
description: "My personal blog"
author:
  name: "Alexander Thulcke"
  url: "https://blog.x4nh43m.ch/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - CNAME
  - README.md
  - scripts

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Alexander Thulcke"
